[package]
name = "kernel"
version = "0.1.0"
authors = ["Alister Lee <alister@dev.shortepic.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4.6", default-features = false }
cortex-a = { path = "../../cortex-a" }
